spring.application.name=enrollment-service
server.port=8083

spring.datasource.url=jdbc:oracle:thin:@<TNS_ALIAS>?TNS_ADMIN=/app/wallet
spring.datasource.username=<DB_USER>
spring.datasource.password=<DB_PASSWORD>
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# URLs de los otros microservicios
# En EC2 reemplaza con la IP privada o pública de tu instancia
services.course-service.url=http://localhost:8081
services.student-service.url=http://localhost:8082

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
