-- ============================================================
-- ENROLLMENT SERVICE - Schema Oracle
-- ============================================================
CREATE SEQUENCE ENROLLMENT_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ENROLLMENT_ITEM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE ENROLLMENTS (
    ID               NUMBER PRIMARY KEY,
    STUDENT_ID       NUMBER        NOT NULL,
    STUDENT_NAME     VARCHAR2(150) NOT NULL,
    STUDENT_EMAIL    VARCHAR2(200) NOT NULL,
    ENROLLMENT_DATE  TIMESTAMP     NOT NULL,
    SUBTOTAL         NUMBER(10,2)  NOT NULL,
    DISCOUNT_PERCENT NUMBER(5,2)   DEFAULT 0,
    DISCOUNT_AMOUNT  NUMBER(10,2)  DEFAULT 0,
    FINAL_COST       NUMBER(10,2)  NOT NULL,
    STATUS           VARCHAR2(20)  DEFAULT 'CONFIRMED' NOT NULL,
    DISCOUNT_CODE    VARCHAR2(50),
    CONSTRAINT chk_enrollment_status CHECK (STATUS IN ('PENDING','CONFIRMED','CANCELLED'))
);

CREATE TABLE ENROLLMENT_ITEMS (
    ID            NUMBER PRIMARY KEY,
    ENROLLMENT_ID NUMBER       NOT NULL,
    COURSE_ID     NUMBER       NOT NULL,
    COURSE_NAME   VARCHAR2(200) NOT NULL,
    INSTRUCTOR    VARCHAR2(150) NOT NULL,
    DURATION_HOURS NUMBER(5)   NOT NULL,
    UNIT_PRICE    NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_item_enrollment FOREIGN KEY (ENROLLMENT_ID) REFERENCES ENROLLMENTS(ID)
);

CREATE INDEX idx_enrollments_student    ON ENROLLMENTS(STUDENT_ID);
CREATE INDEX idx_enrollments_email      ON ENROLLMENTS(STUDENT_EMAIL);
CREATE INDEX idx_enrollment_items_enr   ON ENROLLMENT_ITEMS(ENROLLMENT_ID);
