spring.application.name=course-service
server.port=8081

# Oracle Cloud - Autonomous DB con Wallet
spring.datasource.url=jdbc:oracle:thin:@<TNS_ALIAS>?TNS_ADMIN=/app/wallet
spring.datasource.username=<DB_USER>
spring.datasource.password=<DB_PASSWORD>
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
