oracle.net.wallet_location=(SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY=/app/wallet)))
javax.net.ssl.trustStore=/app/wallet/truststore.jks
javax.net.ssl.trustStorePassword=OracleCloud_2025
javax.net.ssl.keyStore=/app/wallet/keystore.jks
javax.net.ssl.keyStorePassword=OracleCloud_2025